### ISSUE TITLE
Make available on NPM

### ISSUE THREAD

**Issue by dhoko** [kekeh/vsscrollbar#1]
Hi,
it would be great if this would be available via NPM :angel:

**Comment by kekeh** [comment]
Now installation can be done using the **bower**. It installs files from the **dist/debug** and the **dist/min** folders. Needed CSS and javascript files are located in these folders.

bower install vsdatatable

**Comment by kekeh** [comment]
Installation can be done using the bower. It installs files from the dist/debug and the dist/min folders. Needed CSS and javascript files are located in these folders.

example:  "bower install vsscrollbar"

**Comment by dhoko** [comment]
Why not npm to ?
