### ISSUE TITLE
Scroll velocity

### ISSUE THREAD

**Issue by danielgek** [kekeh/vsscrollbar#2]
Hi, 
i wish to know how can i make the scroll a bit less aggressive

can you show me how ?

Thanks in advance ;)

**Comment by kekeh** [comment]
Hi Daniel,

Good question. Velocity depends on the item count in the list (more items and velocity is fast). For example moving the scroll one pixel, moves thousand of items in the list.

I don't have any idea how to fix that, but mousewheel shows all items from the list. Also keyboard arrows can be implemented to do so.

Here is an example: http://embed.plnkr.co/a9U6nX/preview

The first dropdown has one million items and velocity is fast. The second dropdown has 101 items and velocity is normal (one pixel move of the scroll moves the next item from the list).

Was that what you though? If you find out how to fix that, let me know...

**Comment by danielgek** [comment]
well i changed to move only on item a time (its serves the use case), but i will try to figure it out, i saw [this](http://stackoverflow.com/questions/22593286/detect-measure-scroll-speed), and i will try to implement it ;)

**Comment by kekeh** [comment]
After that change verify that you see last items from the list when you drag the scrollbox to the bottom.
